spring:
  application:
    name: ClothingStoreManager

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    #if I use driver-class-name: the ApplicationInitConfig will not be invoked

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

# MYSQL CONNECTION
server:
  port: 4040

app:
  init-admin-account:
    username: ${INIT_ADMIN_ACCOUNT_USERNAME}
    password: ${INIT_ADMIN_ACCOUNT_PASSWORD}
  role:
    admin:
      description: "Admin has all permissions"
    user:
      description: "User has only certain permissions"
  controller:
    user:
      response:
        delete:
          success: "User has been deleted"
    role:
      response:
        delete:
          success: "Role has been deleted"
    employee:
      response:
        delete:
          success: "Employee and its associated account has been deleted"
    authentication:
      response:
        logout:
          success: "Logout successfully"
        change-password:
          success: "Password has been changed"
  cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}